"""add pdf_file_path to investigations model.

Revision ID: 80c8036b4761
Revises: 63ffc62e06da
Create Date: 2026-01-23 19:31:07.814667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c8036b4761'
down_revision: Union[str, Sequence[str], None] = '63ffc62e06da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('pdf_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'pdf_file_path')
    # ### end Alembic commands ###
